[package]
name = "oracle-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false
[dependencies]
oracle-contracts = { path = "../oracle-contracts" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
oracle-task-scope = { path = "../oracle-task-scope" }
